version: '3'

networks:
  spring-rabbitmq:

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    expose:
      - 8333
      - 5672
      - 15672
    ports:
      - 5672:5672
    networks:
      - spring-rabbitmq

  application1:
    build: .
    container_name: application1
    image: spring-rabbitmq
    ports:
      - 8080:8080
    networks:
      - spring-rabbitmq